# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e24e14631734c999b3f2ea73cfabb6e9029d350d1b06e5a4539e787520edcab6ed399493d5dde0a6a7a2473e8abf5755e44c6efaebd7d9c65e1dec9ffd50b9fe

test:
  secret_key_base: 7e60ad10982e77e4a4c11877f41b1dd100dd05085d2450bdaea811c3d9e1f1471e904984cc5bd5b6bcd7950a35e3901801a4b93fb12b4647489d09560914f093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
